### ISSUE TITLE
Cerebro resolves ES domain name to cerebro's docker ip

### ISSUE THREAD

**Issue by wrdls** [yannart/docker-cerebro#20]
_This might be a cerebro issue but its docker related so I'm posting here first._

I have an elasticsearch cluster (with search-guard) with 3 nodes and cerebro running in docker.

I can't connect with cerebro to elasticsearch on the same host as cerebro (e.g. cerebro on elk00 -> es on elk00) but works fine when connecting to another elasticsearch (e.g. cerebro on elk00 -> es on elk01). 

The issue seems that cerebro resolves the domain name to its own docker ip instead of the host ip:
```
[info] play.api.Play - Application started (Prod)
[info] p.c.s.NettyServer - Listening for HTTP on /0.0.0.0:9000
[error] application -

! @77816l344 - Internal server error, for (POST) [/connect] ->

play.api.UnexpectedException: Unexpected exception[ConnectException: Connection refused: elk00.example.com/172.17.0.3:9200]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
Caused by: java.net.ConnectException: Connection refused: elk00.example.com/172.17.0.3:9200
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:160)
	at org.asynchttpclient.netty.request.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:103)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: elk00.example.com/172.17.0.3:9200
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:257)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:291)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
```

cerebro docker ip: 172.17.0.3
es docker ip: 172.17.0.2

es version: 6.2.2
searchguard version: 21
cerebro version: latest (0.7.2)

application.conf hosts:
```
hosts = [
    {
        host = "https://elk00.example.com:9200"
        name = "clustername elk00"
        auth = {
            username = "test"
            password = "test123"
        }
    },
    {
        host = "https://elk01.example.com:9200"
        name = "clustername elk01"
        auth = {
            username = "test"
            password = "test123"
        }
    },
    {
        host = "https://elk02.example.com:9200"
        name = "clustername elk02"
        auth = {
            username = "test"
            password = "test123"
        }
    }
]
```

**Comment by wrdls** [comment]
User error, I set hostname of the container to the domain name.
